language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-mirror-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  global:
    secure: bUjUs1Wto+KI81pPYBI0r5kt5xnHqQDjEYxpcyZCfBX8JRcipd6DbCk3yndkIydYpH68BsOTsNwK76LLwNX2RVaoHUrEnHILzx5lHUChOlmBQ3Lz1gUP4EXidwDK5lIqq649PBEmcZhCy1WwFYLCs062S3ncxUxgz2/r5kiFtPw=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh | bash
notifications:
  slack:
    secure: ejX0ffM0NVSDjbp6hxlScmEzd303xKyhECfeG6Rb6VF3yRZJw46pwHu/p2zi7sbo1ew8Z6hluJ7WIhi1uqVD8JbcXZyn7m5V4Dc93NMCM6xIcjsCQ33wtH+oPWUZqZBsnvJDluU8GD0KhedYx+F+HlL+alP6osvBCgKxcGwbgFY=
