language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  global:
  - secure: KxiwG7bIBhSvrjrvMeEVQs8cTMF0wN0rWsc4R+0CbwyCXxJW0M+NVbhru6Xy8VNIkriBe/ux+zhol1oEkgwJD6aFG1c0JUqXRBGOSMqvKvgEwtbYpoYpRW72s64t1n2wEq6scT1Hd6HNlX2q7KlM2pe8PKAjlwSkVD2LAys8fvk=
  - secure: K7c/g63eG2yEYQCYc51juM7Muif6gO05VC1mVPlFDQ0KgubrCP3jxQ511hq1Y4sR4Uof5ZckNTY3S5vn6QyyMAEiIZI/ZpvZDEcEgVF7bQjePSFlycJZmtninmP+G44FdzsXpCi0n5JGdyP4scCb3UVtTyBeERbG3gJ177kf400=
  - secure: DBV+M07Ro4oGvRw1a47WtAsIK6q5emSTO55DJg8uiL1zi/bX8fB9Ikd4qNnfsLiZtsPte87QZyQvs7mc9I2uEPY9kTKnePp5b+L0hdjGfJ5Ni7HQEYCqxIJsUzI6yy9f5DxZOp89aGn+B/EdkAsZQdB4kQlt+4vMSSskRlNKNxs=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: WNxM0qhBURAwe+tuH/bCpJBU/xUM//ixWk6CkBhKGR8QrA0A9kGrmzx4sbJJ/gCNWQT6JmE4gUxL3765+XqHQbZFZ2WYx2pc3w3FwIqmzXezwmSWWcXDZnMC8ZMsKyCpt7qX0UzaeATGIdwZht/FnKV2jQJIazoHRi/t9TAwbFk=
